const REGIOES = [
  'Grande Florianópolis',
  'Norte',
  'Oeste',
  'Vale do Itajaí',
  'Sul',
  'Serra'
];

const CERTA_DEFAULT_DATA = [
  { municipio: 'Florianópolis', regiao: 'Grande Florianópolis', instituicao: 'CERTA Florianópolis', oficinas: 5, recursoTA: 3, recursosPedagogicos: 4, openDay: 2 },
  { municipio: 'São José', regiao: 'Grande Florianópolis', instituicao: 'Núcleo São José', oficinas: 3, recursoTA: 2, recursosPedagogicos: 2, openDay: 1 },
  { municipio: 'Palhoça', regiao: 'Grande Florianópolis', instituicao: 'Centro Palhoça', oficinas: 2, recursoTA: 1, recursosPedagogicos: 2, openDay: 1 },
  { municipio: 'Biguaçu', regiao: 'Grande Florianópolis', instituicao: 'Instituição Biguaçu', oficinas: 1, recursoTA: 1, recursosPedagogicos: 1, openDay: 0 },
  { municipio: 'Santo Amaro da Imperatriz', regiao: 'Grande Florianópolis', instituicao: 'Centro Santo Amaro', oficinas: 1, recursoTA: 0, recursosPedagogicos: 1, openDay: 0 },
  { municipio: 'São Pedro de Alcântara', regiao: 'Grande Florianópolis', instituicao: 'Instituição São Pedro', oficinas: 0, recursoTA: 0, recursosPedagogicos: 0, openDay: 0 },
  { municipio: 'Antônio Carlos', regiao: 'Grande Florianópolis', instituicao: 'Instituição Antônio Carlos', oficinas: 0, recursoTA: 0, recursosPedagogicos: 0, openDay: 0 },
  { municipio: 'Governador Celso Ramos', regiao: 'Grande Florianópolis', instituicao: 'Centro Celso Ramos', oficinas: 1, recursoTA: 0, recursosPedagogicos: 1, openDay: 0 },
  { municipio: 'Rancho Queimado', regiao: 'Grande Florianópolis', instituicao: 'Instituição Rancho Queimado', oficinas: 0, recursoTA: 0, recursosPedagogicos: 0, openDay: 0 },
  { municipio: 'Águas Mornas', regiao: 'Grande Florianópolis', instituicao: 'Instituição Águas Mornas', oficinas: 0, recursoTA: 0, recursosPedagogicos: 0, openDay: 0 },
  { municipio: 'Garopaba', regiao: 'Grande Florianópolis', instituicao: 'Instituição Garopaba', oficinas: 1, recursoTA: 1, recursosPedagogicos: 1, openDay: 0 },
  { municipio: 'Joinville', regiao: 'Norte', instituicao: 'CERTA Joinville', oficinas: 4, recursoTA: 3, recursosPedagogicos: 2, openDay: 1 },
  { municipio: 'Jaraguá do Sul', regiao: 'Norte', instituicao: 'Instituição Jaraguá', oficinas: 2, recursoTA: 2, recursosPedagogicos: 1, openDay: 1 },
  { municipio: 'São Bento do Sul', regiao: 'Norte', instituicao: 'Instituição São Bento', oficinas: 1, recursoTA: 1, recursosPedagogicos: 1, openDay: 0 },
  { municipio: 'Guaramirim', regiao: 'Norte', instituicao: 'Instituição Guaramirim', oficinas: 1, recursoTA: 0, recursosPedagogicos: 1, openDay: 0 },
  { municipio: 'Massaranduba', regiao: 'Norte', instituicao: 'Instituição Massaranduba', oficinas: 0, recursoTA: 0, recursosPedagogicos: 0, openDay: 0 },
  { municipio: 'Schroeder', regiao: 'Norte', instituicao: 'Instituição Schroeder', oficinas: 0, recursoTA: 0, recursosPedagogicos: 0, openDay: 0 },
  { municipio: 'Araquari', regiao: 'Norte', instituicao: 'Instituição Araquari', oficinas: 1, recursoTA: 0, recursosPedagogicos: 1, openDay: 0 },
  { municipio: 'Corupá', regiao: 'Norte', instituicao: 'Instituição Corupá', oficinas: 0, recursoTA: 0, recursosPedagogicos: 0, openDay: 0 },
  { municipio: 'Barra Velha', regiao: 'Norte', instituicao: 'Instituição Barra Velha', oficinas: 0, recursoTA: 0, recursosPedagogicos: 0, openDay: 0 },
  { municipio: 'São Francisco do Sul', regiao: 'Norte', instituicao: 'Instituição São Francisco', oficinas: 1, recursoTA: 0, recursosPedagogicos: 1, openDay: 0 },
  { municipio: 'Rio Negrinho', regiao: 'Norte', instituicao: 'Instituição Rio Negrinho', oficinas: 0, recursoTA: 0, recursosPedagogicos: 0, openDay: 0 },
  { municipio: 'Itapoá', regiao: 'Norte', instituicao: 'Instituição Itapoá', oficinas: 0, recursoTA: 0, recursosPedagogicos: 0, openDay: 0 },
  { municipio: 'Mafra', regiao: 'Norte', instituicao: 'Instituição Mafra', oficinas: 1, recursoTA: 1, recursosPedagogicos: 1, openDay: 0 },
  { municipio: 'Papanduva', regiao: 'Norte', instituicao: 'Instituição Papanduva', oficinas: 0, recursoTA: 0, recursosPedagogicos: 0, openDay: 0 },
  { municipio: 'Canoinhas', regiao: 'Norte', instituicao: 'Instituição Canoinhas', oficinas: 1, recursoTA: 0, recursosPedagogicos: 1, openDay: 0 },
  { municipio: 'Três Barras', regiao: 'Norte', instituicao: 'Instituição Três Barras', oficinas: 0, recursoTA: 0, recursosPedagogicos: 0, openDay: 0 },
  { municipio: 'Itaiópolis', regiao: 'Norte', instituicao: 'Instituição Itaiópolis', oficinas: 0, recursoTA: 0, recursosPedagogicos: 0, openDay: 0 },
  { municipio: 'Blumenau', regiao: 'Vale do Itajaí', instituicao: 'CERTA Blumenau', oficinas: 3, recursoTA: 2, recursosPedagogicos: 2, openDay: 1 },
  { municipio: 'Brusque', regiao: 'Vale do Itajaí', instituicao: 'Instituição Brusque', oficinas: 2, recursoTA: 1, recursosPedagogicos: 2, openDay: 0 },
  { municipio: 'Gaspar', regiao: 'Vale do Itajaí', instituicao: 'Instituição Gaspar', oficinas: 1, recursoTA: 1, recursosPedagogicos: 1, openDay: 0 },
  { municipio: 'Indaial', regiao: 'Vale do Itajaí', instituicao: 'Instituição Indaial', oficinas: 1, recursoTA: 1, recursosPedagogicos: 1, openDay: 0 },
  { municipio: 'Timbó', regiao: 'Vale do Itajaí', instituicao: 'Instituição Timbó', oficinas: 1, recursoTA: 0, recursosPedagogicos: 1, openDay: 0 },
  { municipio: 'Pomerode', regiao: 'Vale do Itajaí', instituicao: 'Instituição Pomerode', oficinas: 0, recursoTA: 0, recursosPedagogicos: 0, openDay: 0 },
  { municipio: 'Itajaí', regiao: 'Vale do Itajaí', instituicao: 'CERTA Itajaí', oficinas: 3, recursoTA: 2, recursosPedagogicos: 2, openDay: 1 },
  { municipio: 'Balneário Camboriú', regiao: 'Vale do Itajaí', instituicao: 'Instituição Balneário Camboriú', oficinas: 2, recursoTA: 1, recursosPedagogicos: 1, openDay: 1 },
  { municipio: 'Itapema', regiao: 'Vale do Itajaí', instituicao: 'Instituição Itapema', oficinas: 1, recursoTA: 1, recursosPedagogicos: 1, openDay: 0 },
  { municipio: 'Navegantes', regiao: 'Vale do Itajaí', instituicao: 'Instituição Navegantes', oficinas: 1, recursoTA: 0, recursosPedagogicos: 1, openDay: 0 },
  { municipio: 'Penha', regiao: 'Vale do Itajaí', instituicao: 'Instituição Penha', oficinas: 0, recursoTA: 0, recursosPedagogicos: 0, openDay: 0 },
  { municipio: 'Balneário Piçarras', regiao: 'Vale do Itajaí', instituicao: 'Instituição Balneário Piçarras', oficinas: 0, recursoTA: 0, recursosPedagogicos: 0, openDay: 0 },
  { municipio: 'Ilhota', regiao: 'Vale do Itajaí', instituicao: 'Instituição Ilhota', oficinas: 0, recursoTA: 0, recursosPedagogicos: 0, openDay: 0 },
  { municipio: 'Ascurra', regiao: 'Vale do Itajaí', instituicao: 'Instituição Ascurra', oficinas: 0, recursoTA: 0, recursosPedagogicos: 0, openDay: 0 },
  { municipio: 'Rodeio', regiao: 'Vale do Itajaí', instituicao: 'Instituição Rodeio', oficinas: 0, recursoTA: 0, recursosPedagogicos: 0, openDay: 0 },
  { municipio: 'Benedito Novo', regiao: 'Vale do Itajaí', instituicao: 'Instituição Benedito Novo', oficinas: 0, recursoTA: 0, recursosPedagogicos: 0, openDay: 0 },
  { municipio: 'Apiúna', regiao: 'Vale do Itajaí', instituicao: 'Instituição Apiúna', oficinas: 0, recursoTA: 0, recursosPedagogicos: 0, openDay: 0 },
  { municipio: 'Lontras', regiao: 'Vale do Itajaí', instituicao: 'Instituição Lontras', oficinas: 0, recursoTA: 0, recursosPedagogicos: 0, openDay: 0 },
  { municipio: 'Rio do Sul', regiao: 'Vale do Itajaí', instituicao: 'Instituição Rio do Sul', oficinas: 1, recursoTA: 1, recursosPedagogicos: 1, openDay: 0 },
  { municipio: 'Taió', regiao: 'Vale do Itajaí', instituicao: 'Instituição Taió', oficinas: 0, recursoTA: 0, recursosPedagogicos: 0, openDay: 0 },
  { municipio: 'Ibirama', regiao: 'Vale do Itajaí', instituicao: 'Instituição Ibirama', oficinas: 0, recursoTA: 0, recursosPedagogicos: 0, openDay: 0 },
  { municipio: 'Presidente Getúlio', regiao: 'Vale do Itajaí', instituicao: 'Instituição Presidente Getúlio', oficinas: 0, recursoTA: 0, recursosPedagogicos: 0, openDay: 0 },
  { municipio: 'Chapecó', regiao: 'Oeste', instituicao: 'CERTA Chapecó', oficinas: 4, recursoTA: 3, recursosPedagogicos: 3, openDay: 1 },
  { municipio: 'Xanxerê', regiao: 'Oeste', instituicao: 'Instituição Xanxerê', oficinas: 2, recursoTA: 1, recursosPedagogicos: 1, openDay: 0 },
  { municipio: 'Xaxim', regiao: 'Oeste', instituicao: 'Instituição Xaxim', oficinas: 1, recursoTA: 1, recursosPedagogicos: 1, openDay: 0 },
  { municipio: 'Concórdia', regiao: 'Oeste', instituicao: 'Instituição Concórdia', oficinas: 2, recursoTA: 1, recursosPedagogicos: 1, openDay: 1 },
  { municipio: 'Joaçaba', regiao: 'Oeste', instituicao: 'Instituição Joaçaba', oficinas: 1, recursoTA: 1, recursosPedagogicos: 1, openDay: 0 },
  { municipio: 'Caçador', regiao: 'Oeste', instituicao: 'Instituição Caçador', oficinas: 1, recursoTA: 1, recursosPedagogicos: 1, openDay: 0 },
  { municipio: 'Videira', regiao: 'Oeste', instituicao: 'Instituição Videira', oficinas: 1, recursoTA: 1, recursosPedagogicos: 1, openDay: 0 },
  { municipio: 'Campos Novos', regiao: 'Oeste', instituicao: 'Instituição Campos Novos', oficinas: 1, recursoTA: 0, recursosPedagogicos: 1, openDay: 0 },
  { municipio: 'Herval d\'Oeste', regiao: 'Oeste', instituicao: 'Instituição Herval d\'Oeste', oficinas: 0, recursoTA: 0, recursosPedagogicos: 0, openDay: 0 },
  { municipio: 'Seara', regiao: 'Oeste', instituicao: 'Instituição Seara', oficinas: 0, recursoTA: 0, recursosPedagogicos: 0, openDay: 0 },
  { municipio: 'Maravilha', regiao: 'Oeste', instituicao: 'Instituição Maravilha', oficinas: 1, recursoTA: 1, recursosPedagogicos: 1, openDay: 0 },
  { municipio: 'São Miguel do Oeste', regiao: 'Oeste', instituicao: 'Instituição São Miguel', oficinas: 1, recursoTA: 1, recursosPedagogicos: 1, openDay: 0 },
  { municipio: 'Itapiranga', regiao: 'Oeste', instituicao: 'Instituição Itapiranga', oficinas: 0, recursoTA: 0, recursosPedagogicos: 0, openDay: 0 },
  { municipio: 'Palmitos', regiao: 'Oeste', instituicao: 'Instituição Palmitos', oficinas: 0, recursoTA: 0, recursosPedagogicos: 0, openDay: 0 },
  { municipio: 'Quilombo', regiao: 'Oeste', instituicao: 'Instituição Quilombo', oficinas: 0, recursoTA: 0, recursosPedagogicos: 0, openDay: 0 },
  { municipio: 'São Lourenço do Oeste', regiao: 'Oeste', instituicao: 'Instituição São Lourenço', oficinas: 0, recursoTA: 0, recursosPedagogicos: 0, openDay: 0 },
  { municipio: 'Lages', regiao: 'Serra', instituicao: 'CERTA Lages', oficinas: 3, recursoTA: 2, recursosPedagogicos: 2, openDay: 1 },
  { municipio: 'São Joaquim', regiao: 'Serra', instituicao: 'Instituição São Joaquim', oficinas: 1, recursoTA: 1, recursosPedagogicos: 1, openDay: 0 },
  { municipio: 'Curitibanos', regiao: 'Serra', instituicao: 'Instituição Curitibanos', oficinas: 1, recursoTA: 1, recursosPedagogicos: 1, openDay: 0 },
  { municipio: 'Otacílio Costa', regiao: 'Serra', instituicao: 'Instituição Otacílio Costa', oficinas: 0, recursoTA: 0, recursosPedagogicos: 0, openDay: 0 },
  { municipio: 'Correia Pinto', regiao: 'Serra', instituicao: 'Instituição Correia Pinto', oficinas: 0, recursoTA: 0, recursosPedagogicos: 0, openDay: 0 },
  { municipio: 'Urubici', regiao: 'Serra', instituicao: 'Instituição Urubici', oficinas: 1, recursoTA: 0, recursosPedagogicos: 1, openDay: 0 },
  { municipio: 'Urupema', regiao: 'Serra', instituicao: 'Instituição Urupema', oficinas: 0, recursoTA: 0, recursosPedagogicos: 0, openDay: 0 },
  { municipio: 'Bom Jardim da Serra', regiao: 'Serra', instituicao: 'Instituição Bom Jardim', oficinas: 0, recursoTA: 0, recursosPedagogicos: 0, openDay: 0 },
  { municipio: 'Anita Garibaldi', regiao: 'Serra', instituicao: 'Instituição Anita Garibaldi', oficinas: 0, recursoTA: 0, recursosPedagogicos: 0, openDay: 0 },
  { municipio: 'Fraiburgo', regiao: 'Serra', instituicao: 'Instituição Fraiburgo', oficinas: 1, recursoTA: 1, recursosPedagogicos: 1, openDay: 0 },
  { municipio: 'Água Doce', regiao: 'Serra', instituicao: 'Instituição Água Doce', oficinas: 0, recursoTA: 0, recursosPedagogicos: 0, openDay: 0 },
  { municipio: 'Porto União', regiao: 'Serra', instituicao: 'Instituição Porto União', oficinas: 0, recursoTA: 0, recursosPedagogicos: 0, openDay: 0 },
  { municipio: 'Rio do Campo', regiao: 'Vale do Itajaí', instituicao: 'Instituição Rio do Campo', oficinas: 0, recursoTA: 0, recursosPedagogicos: 0, openDay: 0 },
  { municipio: 'Salete', regiao: 'Vale do Itajaí', instituicao: 'Instituição Salete', oficinas: 0, recursoTA: 0, recursosPedagogicos: 0, openDay: 0 },
  { municipio: 'Agronômica', regiao: 'Vale do Itajaí', instituicao: 'Instituição Agronômica', oficinas: 0, recursoTA: 0, recursosPedagogicos: 0, openDay: 0 },
  { municipio: 'Laurentino', regiao: 'Vale do Itajaí', instituicao: 'Instituição Laurentino', oficinas: 0, recursoTA: 0, recursosPedagogicos: 0, openDay: 0 },
  { municipio: 'Aurora', regiao: 'Vale do Itajaí', instituicao: 'Instituição Aurora', oficinas: 0, recursoTA: 0, recursosPedagogicos: 0, openDay: 0 },
  { municipio: 'Ituporanga', regiao: 'Vale do Itajaí', instituicao: 'Instituição Ituporanga', oficinas: 0, recursoTA: 0, recursosPedagogicos: 0, openDay: 0 },
  { municipio: 'Alfredo Wagner', regiao: 'Vale do Itajaí', instituicao: 'Instituição Alfredo Wagner', oficinas: 0, recursoTA: 0, recursosPedagogicos: 0, openDay: 0 },
  { municipio: 'Vidal Ramos', regiao: 'Vale do Itajaí', instituicao: 'Instituição Vidal Ramos', oficinas: 0, recursoTA: 0, recursosPedagogicos: 0, openDay: 0 },
  { municipio: 'Nova Trento', regiao: 'Vale do Itajaí', instituicao: 'Instituição Nova Trento', oficinas: 0, recursoTA: 0, recursosPedagogicos: 0, openDay: 0 },
  { municipio: 'Tijucas', regiao: 'Grande Florianópolis', instituicao: 'Instituição Tijucas', oficinas: 1, recursoTA: 0, recursosPedagogicos: 1, openDay: 0 },
  { municipio: 'São João Batista', regiao: 'Grande Florianópolis', instituicao: 'Instituição São João Batista', oficinas: 0, recursoTA: 0, recursosPedagogicos: 0, openDay: 0 },
  { municipio: 'Canelinha', regiao: 'Grande Florianópolis', instituicao: 'Instituição Canelinha', oficinas: 0, recursoTA: 0, recursosPedagogicos: 0, openDay: 0 },
  { municipio: 'Major Gercino', regiao: 'Grande Florianópolis', instituicao: 'Instituição Major Gercino', oficinas: 0, recursoTA: 0, recursosPedagogicos: 0, openDay: 0 },
  { municipio: 'Criciúma', regiao: 'Sul', instituicao: 'CERTA Criciúma', oficinas: 3, recursoTA: 2, recursosPedagogicos: 2, openDay: 1 },
  { municipio: 'Tubarão', regiao: 'Sul', instituicao: 'Instituição Tubarão', oficinas: 2, recursoTA: 1, recursosPedagogicos: 1, openDay: 1 },
  { municipio: 'Araranguá', regiao: 'Sul', instituicao: 'Instituição Araranguá', oficinas: 2, recursoTA: 1, recursosPedagogicos: 1, openDay: 0 },
  { municipio: 'Laguna', regiao: 'Sul', instituicao: 'Instituição Laguna', oficinas: 1, recursoTA: 1, recursosPedagogicos: 1, openDay: 0 },
  { municipio: 'Imbituba', regiao: 'Sul', instituicao: 'Instituição Imbituba', oficinas: 1, recursoTA: 1, recursosPedagogicos: 1, openDay: 0 },
  { municipio: 'Imaruí', regiao: 'Sul', instituicao: 'Instituição Imaruí', oficinas: 0, recursoTA: 0, recursosPedagogicos: 0, openDay: 0 },
  { municipio: 'Içara', regiao: 'Sul', instituicao: 'Instituição Içara', oficinas: 1, recursoTA: 1, recursosPedagogicos: 1, openDay: 0 },
  { municipio: 'Forquilhinha', regiao: 'Sul', instituicao: 'Instituição Forquilhinha', oficinas: 0, recursoTA: 0, recursosPedagogicos: 0, openDay: 0 },
  { municipio: 'Sombrio', regiao: 'Sul', instituicao: 'Instituição Sombrio', oficinas: 0, recursoTA: 0, recursosPedagogicos: 0, openDay: 0 }
];
